export const SKILLS = [
  { name: 'aurelia', label: 'Aurelia', link: 'https://aurelia.io/' },
  { name: 'angular', label: 'Angular', link: 'https://angular.io/' },
  { name: 'aws', label: 'AWS', link: 'https://aws.amazon.com/' },
  { name: 'css3', label: 'CSS3', link: 'https://en.wikipedia.org/wiki/CSS' },
  { name: 'docker', label: 'Docker', link: 'https://www.docker.com/' },
  { name: 'electron', label: 'Electron', link: 'https://www.electronjs.org/' },
  { name: 'expressjs', label: 'ExpressJS', link: 'https://expressjs.com/' },
  { name: 'git', label: 'Git', link: 'https://git-scm.com/' },
  { name: 'gulp', label: 'Gulp', link: 'https://gulpjs.com/' },
  { name: 'html5', label: 'HTML5', link: 'https://en.wikipedia.org/wiki/HTML5' },
  { name: 'javascript', label: 'JavaScript', link: 'https://www.javascript.com/' },
  { name: 'jenkins', label: 'Jenkins', link: 'https://www.jenkins.io/' },
  { name: 'jwt', label: 'JSON Web Tokens', link: 'https://jwt.io/' },
  { name: 'kubernetes', label: 'Kubernetes', link: 'https://kubernetes.io/' },
  { name: 'mongodb', label: 'Mongo DB', link: 'https://www.mongodb.com/' },
  { name: 'nodejs', label: 'NodeJS', link: 'https://nodejs.org/' },
  { name: 'rabbitmq', label: 'RabbitMQ', link: 'https://www.rabbitmq.com/' },
  { name: 'react', label: 'React', link: 'https://reactjs.org/' },
  { name: 'redux', label: 'Redux', link: 'https://redux.js.org/' },
  { name: 'rxjs', label: 'RxJS', link: 'https://angular.io/guide/rx-library' },
  { name: 'typescript', label: 'TypeScript', link: 'https://www.typescriptlang.org/' },
  { name: 'vue-js', label: 'VueJS', link: 'https://vuejs.org/' },
  { name: 'webpack', label: 'Webpack', link: 'https://webpack.js.org/' },
  { name: 'webrtc', label: 'Webrtc', link: 'https://webrtc.org/' },
  { name: 'wordpress', label: 'Wordpress', link: 'https://wordpress.com/' }
];