export const SKILLS = [
  { img: 'aurelia.png', label: 'Aurelia', link: 'https://aurelia.io/' },
  { img: 'angular.webp', label: 'Angular', link: 'https://angular.io/' },
  { img: 'aws.png', label: 'AWS', link: 'https://aws.amazon.com/' },
  { img: 'css3.webp', label: 'CSS3', link: 'https://en.wikipedia.org/wiki/CSS' },
  { img: 'docker.png', label: 'Docker', link: 'https://www.docker.com/' },
  { img: 'electron.png', label: 'Electron', link: 'https://www.electronjs.org/' },
  { img: 'expressjs.svg', label: 'ExpressJS', link: 'https://expressjs.com/' },
  { img: 'git.png', label: 'Git', link: 'https://git-scm.com/' },
  { img: 'gulp.png', label: 'Gulp', link: 'https://gulpjs.com/' },
  { img: 'html5.png', label: 'HTML5', link: 'https://en.wikipedia.org/wiki/HTML5' },
  { img: 'javascript.png', label: 'JavaScript', link: 'https://www.javascript.com/' },
  { img: 'jenkins.jpg', label: 'Jenkins', link: 'https://www.jenkins.io/' },
  { img: 'jwt.png', label: 'JSON Web Tokens', link: 'https://jwt.io/' },
  { img: 'kubernetes.png', label: 'Kubernetes', link: 'https://kubernetes.io/' },
  { img: 'mongodb.png', label: 'Mongo DB', link: 'https://www.mongodb.com/' },
  { img: 'nodejs.png', label: 'NodeJS', link: 'https://nodejs.org/' },
  { img: 'rabbitmq.png', label: 'RabbitMQ', link: 'https://www.rabbitmq.com/' },
  { img: 'react.png', label: 'React', link: 'https://reactjs.org/' },
  { img: 'redux.png', label: 'Redux', link: 'https://redux.js.org/' },
  { img: 'rxjs.png', label: 'RxJS', link: 'https://angular.io/guide/rx-library' },
  { img: 'typescript.png', label: 'TypeScript', link: 'https://www.typescriptlang.org/' },
  { img: 'vue-js.png', label: 'VueJS', link: 'https://vuejs.org/' },
  { img: 'webpack.png', label: 'Webpack', link: 'https://webpack.js.org/' },
  { img: 'webrtc.png', label: 'Webrtc', link: 'https://webrtc.org/' },
  { img: 'wordpress.png', label: 'Wordpress', link: 'https://wordpress.com/' }
];